name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'core/**'
      - 'studio/app/frontend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'core/**'
      - 'studio/app/frontend/**'

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '20.x'

jobs:
  # Build and test C# Worker
  build-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

  # Build and typecheck frontend
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: studio/app/frontend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: studio/app/frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript type check
        run: npm run typecheck
      
      - name: Lint
        run: npm run lint --if-present
      
      - name: Build
        run: npm run build

  # Ensure TypeScript types are in sync with OpenAPI spec
  check-types-sync:
    runs-on: ubuntu-latest
    needs: [build-worker]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: studio/app/frontend/package-lock.json
      
      - name: Build Worker
        working-directory: core
        run: dotnet build --configuration Release
      
      - name: Start Worker (background)
        working-directory: core
        run: |
          dotnet run --project src/BitingLip.Core.Worker --configuration Release --no-build &
          # Wait for server to start
          for i in {1..30}; do
            if curl -s http://localhost:8081/health > /dev/null 2>&1; then
              echo "Worker is ready"
              break
            fi
            echo "Waiting for worker... ($i/30)"
            sleep 1
          done
      
      - name: Install frontend dependencies
        working-directory: studio/app/frontend
        run: npm ci
      
      - name: Generate types from OpenAPI
        working-directory: studio/app/frontend
        run: npm run generate:types
      
      - name: Check for uncommitted type changes
        working-directory: studio/app/frontend
        run: |
          if git diff --exit-code types/api-generated.ts; then
            echo "✅ Types are in sync with OpenAPI spec"
          else
            echo "❌ Types are out of sync! Run 'npm run generate:types' locally and commit the changes."
            exit 1
          fi
